from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from .. import models, schemas, pricing
from ..database import get_db

router = APIRouter(prefix="/api", tags=["recommendations"])

# Weights for the match score. Documented and simple by design — this is
# an academic ranking heuristic, not a learned recommender model. It is
# separate from (and reuses the output of) the trained regression model
# in pricing.py, which supplies the "fair price" used to flag good deals.
W_BUDGET_FIT = 0.35
W_VALUE = 0.30
W_RATING = 0.25
W_CAPACITY_FIT = 0.10

GREAT_VALUE_THRESHOLD = 0.90  # actual price <= 90% of the model's fair-price estimate


def generate_recommendations(db: Session, budget_min: float, budget_max: float, guests: int,
                              city: str | None = None, room_type: str | None = None, limit: int = 12):
    """
    Shared scoring engine used by both POST /api/recommendations (the
    guest-facing "Find your match" page) and the chatbot
    (routers/chatbot.py), so there is exactly one ranking
    implementation backing both entry points — not two divergent ones.
    """
    query = db.query(models.Listing).filter(
        models.Listing.accommodates >= guests,
        models.Listing.price <= budget_max * 1.15,
    )
    if city:
        query = query.filter(models.Listing.city == city)
    if room_type:
        query = query.filter(models.Listing.room_type == room_type)

    candidates = query.limit(200).all()  # bounded scan, not the full table
    total_candidates = len(candidates)

    scored = []
    for listing in candidates:
        fair_price = pricing.estimate_price(
            city=listing.city,
            property_type=listing.property_type,
            room_type=listing.room_type,
            accommodates=listing.accommodates,
            bedrooms=listing.bedrooms,
            minimum_nights=listing.minimum_nights,
            review_scores_rating=listing.review_scores_rating or 4.0,
        )

        if budget_min <= listing.price <= budget_max:
            budget_fit = 1.0
        elif listing.price < budget_min:
            budget_fit = max(0.0, 1.0 - (budget_min - listing.price) / max(budget_min, 1))
        else:
            budget_fit = max(0.0, 1.0 - (listing.price - budget_max) / max(budget_max, 1))

        value_ratio = (fair_price - listing.price) / fair_price if fair_price > 0 else 0
        value_score = min(1.0, max(0.0, value_ratio + 0.5))

        rating_score = (listing.review_scores_rating or 3.5) / 5.0

        extra_capacity = listing.accommodates - guests
        capacity_fit = 1.0 if extra_capacity == 0 else max(0.3, 1.0 - extra_capacity * 0.1)

        match_score = (
            W_BUDGET_FIT * budget_fit
            + W_VALUE * value_score
            + W_RATING * rating_score
            + W_CAPACITY_FIT * capacity_fit
        )

        is_great_value = listing.price <= fair_price * GREAT_VALUE_THRESHOLD

        reasons = []
        if budget_fit >= 0.99:
            reasons.append("within your budget")
        if is_great_value:
            reasons.append("priced below its estimated market value")
        if (listing.review_scores_rating or 0) >= 4.7:
            reasons.append("highly rated")
        if extra_capacity == 0:
            reasons.append("exact guest capacity match")
        match_reason = ", ".join(reasons) if reasons else "closest overall match to your criteria"

        listing_data = schemas.ListingOut.model_validate(listing).model_dump()
        scored.append((match_score, schemas.RecommendedListing(
            **listing_data,
            fair_price_estimate=fair_price,
            is_great_value=is_great_value,
            match_reason=match_reason,
        )))

    scored.sort(key=lambda pair: pair[0], reverse=True)
    return total_candidates, [item for _, item in scored[:limit]]


@router.post("/recommendations", response_model=schemas.RecommendationResponse)
def get_recommendations(payload: schemas.RecommendationRequest, db: Session = Depends(get_db)):
    total_candidates, top_results = generate_recommendations(
        db, payload.budget_min, payload.budget_max, payload.guests, payload.city, payload.room_type,
    )
    return schemas.RecommendationResponse(
        total_candidates=total_candidates,
        results=top_results,
        disclaimer=(
            "Recommendations are generated by a simple academic ranking rule combining "
            "budget fit, estimated value, rating and capacity match. This is not a "
            "production recommender system and should not be treated as an objective "
            "quality judgement — see docs/RESPONSIBLE_AI.md."
        ),
    )
